// Driftcore Vizdev Moodboard — Cloudflare Worker
// Proxies image generation to Krea (https://docs.krea.ai), stores images in R2,
// and metadata in KV. Serves the static frontend from the ASSETS binding.

export interface Env {
  KREA_API_KEY: string;
  // fal.ai key for the 3D pipeline. Krea's public REST API doesn't expose
  // image-to-3D, so we delegate that step to fal.ai. Set with:
  //   wrangler secret put FAL_API_KEY
  FAL_API_KEY: string;
  IMAGES: R2Bucket;
  STATE: KVNamespace;
  ASSETS: Fetcher;
}

interface ImageMeta {
  id: string;
  subjectId: string;
  r2Key: string;
  prompt: string;
  model: string;
  width: number;
  height: number;
  steps: number;
  seed?: number;
  createdAt: number;
  favorite: boolean;
  // Derivative-view fields. Set when this image is generated by /api/views/generate
  // from another image. Original "primary" generations leave these undefined.
  parentImageId?: string;
  view?: string; // "front" | "back" | "top" | "three_quarter" | etc.
}

interface MeshMeta {
  id: string;
  // The favorite image(s) used as input. First entry is the primary; subsequent
  // entries are extra views (front/back/top/etc) when supported by the model.
  sourceImageIds: string[];
  r2Key: string;
  format: string; // "glb" | "obj" | etc.
  model: string;
  createdAt: number;
  // Set when this mesh was produced by a remesh / topology pass on another
  // mesh. The Pipeline tab shows remeshed children grouped under their parent.
  parentMeshId?: string;
}

interface Settings {
  preamble?: string;
  // Per-kind preamble overrides. Keyed by subject `type` ("weapon", "augment",
  // etc). Falls back to catalog.kind_preambles[kind], then settings.preamble,
  // then catalog.settings.preamble. Resolved on the frontend.
  kind_preambles?: Record<string, string>;
  model?: string;
  width?: number;
  height?: number;
  steps?: number;
  count?: number;
  styleStrength?: number;
  meshModel?: string;
}

// Persistent generation job. Survives page refresh and worker restarts (KV).
// `ctx.waitUntil` keeps the worker alive long enough to poll Krea after the
// HTTP response has been sent — see startJob.
interface JobMeta {
  id: string;
  kind: "image" | "view" | "mesh" | "remesh";
  status: "queued" | "processing" | "completed" | "failed";
  // Human-readable progress hint, updated as the worker polls Krea / fal.
  progress?: string;
  error?: string;
  // KV id of the resulting ImageMeta or MeshMeta. Set when status=completed.
  resultId?: string;
  // Subject id (for image/view jobs) so the frontend can group pending thumbs.
  subjectId?: string;
  // Parent image id for view jobs so the Pipeline tab can slot the placeholder.
  parentImageId?: string;
  view?: string;
  // The original request params, kept in case we need to retry or surface them.
  params: Record<string, unknown>;
  // For fal-backed jobs (mesh / remesh) we capture the cancel URL fal returns
  // on submit so /api/job/:id/cancel can actually stop the upstream work
  // instead of just removing the local placeholder.
  falCancelUrl?: string;
  // For mesh/remesh jobs we drive polling from the frontend (each
  // /api/job/:id GET pokes fal once) instead of holding the worker open via
  // ctx.waitUntil for 5+ minutes — Cloudflare evicts long-idle isolates and
  // the runner silently dies. Storing the status_url + response_url + model
  // slug on the JobMeta lets a fresh worker invocation continue the work.
  falStatusUrl?: string;
  falResponseUrl?: string;
  falModel?: string;            // adapter key — determines mesh URL extraction
  falKind?: "mesh" | "remesh";  // remesh has fixed extraction; mesh uses adapter
  // Provider-side status from fal's queue (`IN_QUEUE`, `IN_PROGRESS`,
  // `COMPLETED`, `FAILED`, `ERROR`, `CANCELLED`). This is upstream truth,
  // distinct from our own `status` field which only tracks runner liveness.
  // Together with `updatedAt` they answer two different questions:
  // "is fal making progress?" and "did our worker poll recently?"
  falStatus?: string;
  falQueuePosition?: number;
  // Throttle marker for handleJobGet — only re-poll fal if more than ~2.5s
  // elapsed since the last fal hit, so multiple frontend polls don't hammer.
  falLastPolledAt?: number;
  createdAt: number;
  updatedAt: number;
}

const KREA_BASE = "https://api.krea.ai";
const KV_SETTINGS = "settings";
const KV_OVERRIDES = "overrides";
const KV_IMAGE_INDEX = "image-index"; // string[] of image ids
const KV_MESH_INDEX = "mesh-index";   // string[] of mesh ids
const KV_JOB_INDEX = "job-index";     // string[] of job ids that are not yet
                                      // status=completed (active queue).
const JOB_STALE_MS = 15 * 60 * 1000;  // jobs older than 15 min with no terminal
                                      // status are considered stuck (worker
                                      // probably died mid-flight) and surface
                                      // a clean error to the frontend.

const json = (data: unknown, init?: ResponseInit) =>
  new Response(JSON.stringify(data), {
    ...init,
    headers: { "content-type": "application/json", ...(init?.headers || {}) },
  });

const err = (status: number, message: string) =>
  json({ error: message }, { status });

export default {
  async fetch(req: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(req.url);
    const { pathname } = url;

    try {
      if (pathname === "/api/state" && req.method === "GET") return await handleState(env);
      if (pathname === "/api/settings" && req.method === "POST") return await handleSettings(req, env);
      if (pathname === "/api/prompt" && req.method === "POST") return await handlePromptOverride(req, env);
      if (pathname === "/api/generate" && req.method === "POST") return await handleGenerate(req, env, ctx);
      if (pathname === "/api/favorite" && req.method === "POST") return await handleFavorite(req, env);
      if (pathname === "/api/views/generate" && req.method === "POST") return await handleViewsGenerate(req, env, ctx);
      if (pathname === "/api/mesh/generate" && req.method === "POST") return await handleMeshGenerate(req, env, ctx);
      if (pathname === "/api/mesh/remesh" && req.method === "POST") return await handleMeshRemesh(req, env, ctx);
      if (pathname.startsWith("/api/job/") && pathname.endsWith("/cancel") && req.method === "POST") {
        const id = pathname.slice("/api/job/".length, -"/cancel".length);
        return await handleJobCancel(id, env);
      }
      if (pathname.startsWith("/api/job/") && req.method === "GET") return await handleJobGet(pathname.slice("/api/job/".length), env);
      if (pathname.startsWith("/api/job/") && req.method === "DELETE") return await handleJobDelete(pathname.slice("/api/job/".length), env);
      if (pathname.startsWith("/api/mesh/") && req.method === "DELETE") return await handleMeshDelete(pathname.slice("/api/mesh/".length), env);
      if (pathname.startsWith("/api/image/") && req.method === "DELETE") return await handleDelete(pathname.slice("/api/image/".length), env);
      if (pathname.startsWith("/img/")) return await handleImage(pathname.slice("/img/".length), env);
      if (pathname.startsWith("/mesh/")) return await handleMesh(pathname.slice("/mesh/".length), env);
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      return err(500, message);
    }

    // Fall through to static assets
    return env.ASSETS.fetch(req);
  },
};

async function handleState(env: Env): Promise<Response> {
  const [settings, overrides, imageIndex, meshIndex, jobIndex] = await Promise.all([
    env.STATE.get(KV_SETTINGS, "json") as Promise<Settings | null>,
    env.STATE.get(KV_OVERRIDES, "json") as Promise<Record<string, string> | null>,
    env.STATE.get(KV_IMAGE_INDEX, "json") as Promise<string[] | null>,
    env.STATE.get(KV_MESH_INDEX, "json") as Promise<string[] | null>,
    env.STATE.get(KV_JOB_INDEX, "json") as Promise<string[] | null>,
  ]);
  const ids = imageIndex ?? [];
  const meshIds = meshIndex ?? [];
  const jobIds = jobIndex ?? [];
  // Batch fetches: KV doesn't have getMulti, so do them in parallel.
  const [imageMetas, meshMetas, jobMetas] = await Promise.all([
    Promise.all(ids.map(id => env.STATE.get(`image:${id}`, "json") as Promise<ImageMeta | null>)),
    Promise.all(meshIds.map(id => env.STATE.get(`mesh:${id}`, "json") as Promise<MeshMeta | null>)),
    Promise.all(jobIds.map(id => env.STATE.get(`job:${id}`, "json") as Promise<JobMeta | null>)),
  ]);
  const images: ImageMeta[] = imageMetas.filter((m): m is ImageMeta => !!m);
  const meshes: MeshMeta[] = meshMetas.filter((m): m is MeshMeta => !!m);
  // Surface stale jobs as failures rather than letting them sit in "processing" forever.
  const now = Date.now();
  const jobs: JobMeta[] = [];
  for (const j of jobMetas) {
    if (!j) continue;
    if ((j.status === "queued" || j.status === "processing") && now - j.updatedAt > JOB_STALE_MS) {
      jobs.push({ ...j, status: "failed", error: "Job stalled — worker likely died mid-poll. Retry the generation." });
    } else {
      jobs.push(j);
    }
  }
  return json({
    settings: settings ?? {},
    overrides: overrides ?? {},
    images,
    meshes,
    jobs,
  });
}

async function handleSettings(req: Request, env: Env): Promise<Response> {
  const body = await req.json() as Settings;
  await env.STATE.put(KV_SETTINGS, JSON.stringify(body));
  return json({ ok: true });
}

async function handlePromptOverride(req: Request, env: Env): Promise<Response> {
  const { subjectId, prompt } = await req.json() as { subjectId: string; prompt: string };
  if (!subjectId) return err(400, "subjectId required");
  const overrides = (await env.STATE.get(KV_OVERRIDES, "json") as Record<string, string> | null) ?? {};
  if (prompt && prompt.trim()) {
    overrides[subjectId] = prompt;
  } else {
    delete overrides[subjectId];
  }
  await env.STATE.put(KV_OVERRIDES, JSON.stringify(overrides));
  return json({ ok: true });
}

async function handleGenerate(req: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
  const body = await req.json() as {
    subjectId: string;
    prompt: string;
    model: string;
    width: number;
    height: number;
    steps: number;
    styleImageUrl?: string;
    styleStrength?: number;
  };
  if (!body.subjectId || !body.prompt) return err(400, "subjectId and prompt required");

  const job = await startJob(env, ctx, {
    kind: "image",
    subjectId: body.subjectId,
    params: body as unknown as Record<string, unknown>,
    runner: async (update) => {
      let styleImages: { url: string; strength: number }[] | undefined;
      let outWidth = body.width;
      let outHeight = body.height;
      if (body.styleImageUrl) {
        await update("Uploading style ref to Krea…");
        const ref = await ensureKreaAsset(env, body.styleImageUrl);
        styleImages = [{ url: ref.url, strength: body.styleStrength ?? 0.7 }];
        // Output resolution must never shrink below the reference image, or
        // some models will lock the output to the ref's dimensions and the
        // result looks low-res. Floor at the larger of (user pick, ref dims).
        if (ref.width && ref.width > outWidth) outWidth = ref.width;
        if (ref.height && ref.height > outHeight) outHeight = ref.height;
      }
      await update("Submitting to Krea…");
      const krea = await kreaGenerate(env.KREA_API_KEY, body.model, {
        prompt: body.prompt,
        width: outWidth,
        height: outHeight,
        steps: body.steps,
        styleImages,
      }, update);
      await update("Saving result…");
      const meta = await persistGeneratedImage(env, krea.urls[0], krea.seed, {
        subjectId: body.subjectId,
        prompt: body.prompt,
        model: body.model,
        width: body.width,
        height: body.height,
        steps: body.steps,
      });
      if (!meta) throw new Error("Krea returned no image URL");
      return meta.id;
    },
  });
  return json(job);
}

async function handleFavorite(req: Request, env: Env): Promise<Response> {
  const { id, value } = await req.json() as { id: string; value: boolean };
  if (!id) return err(400, "id required");
  const meta = await env.STATE.get(`image:${id}`, "json") as ImageMeta | null;
  if (!meta) return err(404, "image not found");
  meta.favorite = !!value;
  await env.STATE.put(`image:${id}`, JSON.stringify(meta));
  return json(meta);
}

async function handleDelete(id: string, env: Env): Promise<Response> {
  const meta = await env.STATE.get(`image:${id}`, "json") as ImageMeta | null;
  if (!meta) return err(404, "image not found");
  // Cascade: also delete derivative views that reference this image as parent.
  const indexAll = (await env.STATE.get(KV_IMAGE_INDEX, "json") as string[] | null) ?? [];
  const cascadeIds: string[] = [];
  await Promise.all(indexAll.map(async other => {
    if (other === id) return;
    const m = await env.STATE.get(`image:${other}`, "json") as ImageMeta | null;
    if (m?.parentImageId === id) cascadeIds.push(other);
  }));

  const deletions: Promise<unknown>[] = [
    env.IMAGES.delete(meta.r2Key),
    env.STATE.delete(`image:${id}`),
  ];
  for (const cid of cascadeIds) {
    const cm = await env.STATE.get(`image:${cid}`, "json") as ImageMeta | null;
    if (cm) {
      deletions.push(env.IMAGES.delete(cm.r2Key));
      deletions.push(env.STATE.delete(`image:${cid}`));
    }
  }
  await Promise.all(deletions);
  const removed = new Set([id, ...cascadeIds]);
  await env.STATE.put(KV_IMAGE_INDEX, JSON.stringify(indexAll.filter(x => !removed.has(x))));
  return json({ ok: true, cascaded: cascadeIds.length });
}

async function handleImage(key: string, env: Env): Promise<Response> {
  const decoded = decodeURIComponent(key);
  const obj = await env.IMAGES.get(decoded);
  if (!obj) return err(404, "image not found");
  const headers = new Headers();
  obj.writeHttpMetadata(headers);
  headers.set("etag", obj.httpEtag);
  headers.set("cache-control", "public, max-age=31536000, immutable");
  return new Response(obj.body, { headers });
}

async function handleMesh(key: string, env: Env): Promise<Response> {
  const decoded = decodeURIComponent(key);
  const obj = await env.IMAGES.get(decoded);
  if (!obj) return err(404, "mesh not found");
  const headers = new Headers();
  obj.writeHttpMetadata(headers);
  headers.set("etag", obj.httpEtag);
  headers.set("cache-control", "public, max-age=31536000, immutable");
  // model-viewer needs CORS to be permissive even on same-origin some browsers
  headers.set("access-control-allow-origin", "*");
  return new Response(obj.body, { headers });
}

// ---------- Derivative views (image edit) ----------

// View-edit prompts.
//
// These run on `google/nano-banana-pro` (Gemini 2.5 Flash Image) by default.
// That model is *much* stronger than flux-1-kontext-dev at "same subject, new
// angle" — flux-kontext drifts wildly when asked to rotate. nano-banana-pro
// responds well to plain-language editing instructions; the tone here is
// deliberate (imperative, identity-first).
//
// Identity preservation is everything. The model gets the source image as
// `imageUrls[0]`; the prompt's job is to lock the silhouette / colors /
// proportions and only change the camera angle.

const VIEW_PROMPTS: Record<string, (originalPrompt: string) => string> = {
  front: (p) =>
    "Take the attached reference image. Show me the EXACT SAME subject — same colors, same proportions, same silhouette personality, same surface details, same scale — but rotated so it is facing the viewer directly head-on. This is a clean front elevation: the subject is now looking straight at the camera. Keep the flat magenta (#FF00FF) backdrop, identical lighting, identical 2D painted illustration style. Do NOT change the subject's identity, palette, or detailing. Do NOT add new elements, hardware, environment, or characters. The result must be unmistakably the same subject, just turned 90 degrees so we see its front instead of its side.\n\nFor grounding, here is how the original side-view subject was described: " +
    p.slice(0, 700),
  back: (p) =>
    "Take the attached reference image. Show me the EXACT SAME subject — same colors, same proportions, same silhouette personality, same surface details, same scale — but rotated 180 degrees so we see it from behind. This is a clean back elevation: the subject's tail / rear / spine is facing the viewer. Keep the flat magenta (#FF00FF) backdrop, identical lighting, identical 2D painted illustration style. Do NOT change the subject's identity, palette, or detailing. Do NOT add new elements. The result must be unmistakably the same subject, just turned around so we see the back.\n\nFor grounding, here is how the original side-view subject was described: " +
    p.slice(0, 700),
  top: (p) =>
    "Take the attached reference image. Show me the EXACT SAME subject — same colors, same proportions, same surface details, same scale — but viewed from directly above, as a clean top-down orthographic. This is a flat overhead view: imagine the camera is straight up. Keep the flat magenta (#FF00FF) backdrop, identical lighting, identical 2D painted illustration style. Do NOT change the subject's identity, palette, or detailing. Do NOT add new elements. The result must be unmistakably the same subject, just seen from above.\n\nFor grounding, here is how the original side-view subject was described: " +
    p.slice(0, 700),
  three_quarter: (p) =>
    "Take the attached reference image. Show me the EXACT SAME subject — same colors, same proportions, same silhouette personality, same surface details, same scale — but rotated 30-45 degrees toward the camera so we see both its side AND its front. This is a clean three-quarter view (front-three-quarter, not isometric, not from above). Keep the flat magenta (#FF00FF) backdrop, identical lighting, identical 2D painted illustration style. Do NOT change the subject's identity, palette, or detailing. Do NOT add new elements. The result must be unmistakably the same subject, just rotated so we see two of its faces at once.\n\nFor grounding, here is how the original side-view subject was described: " +
    p.slice(0, 700),
};

async function handleViewsGenerate(req: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
  const body = await req.json() as {
    sourceImageId: string;
    view: string;
    model?: string;
    steps?: number;
  };
  if (!body.sourceImageId || !body.view) return err(400, "sourceImageId and view required");
  const promptBuilder = VIEW_PROMPTS[body.view];
  if (!promptBuilder) return err(400, `unknown view: ${body.view}. Allowed: ${Object.keys(VIEW_PROMPTS).join(", ")}`);

  const source = await env.STATE.get(`image:${body.sourceImageId}`, "json") as ImageMeta | null;
  if (!source) return err(404, "source image not found");

  const job = await startJob(env, ctx, {
    kind: "view",
    subjectId: source.subjectId,
    parentImageId: source.id,
    view: body.view,
    params: body as unknown as Record<string, unknown>,
    runner: async (update) => {
      await update("Uploading source to Krea…");
      const ref = await kreaAssetFromR2(env, source.r2Key);
      const prompt = promptBuilder(source.prompt);
      // Default to nano-banana-pro: it's *much* stronger at identity-preserving
      // rotation than flux-1-kontext-dev. flux-kontext is good for prompt-style
      // edits but drifts wildly when asked to rotate. The frontend exposes the
      // slug as a setting (state.settings.viewsModel) so it's overridable.
      const model = body.model || "google/nano-banana-pro";
      await update(`Submitting view edit to Krea (${model})…`);
      const krea = await kreaGenerate(env.KREA_API_KEY, model, {
        prompt,
        width: source.width,
        height: source.height,
        steps: body.steps ?? 25,
        // Pass the source via BOTH params; the model dispatch in kreaGenerate
        // picks whichever the chosen model accepts (imageUrl for flux-kontext,
        // imageUrls for nano-banana / seedream).
        imageUrl: ref.url,
        imageUrls: [ref.url],
      }, update);
      await update("Saving derivative view…");
      const meta = await persistGeneratedImage(env, krea.urls[0], krea.seed, {
        subjectId: source.subjectId,
        prompt,
        model,
        width: source.width,
        height: source.height,
        steps: body.steps ?? 25,
        parentImageId: source.id,
        view: body.view,
      });
      if (!meta) throw new Error("Krea returned no image URL");
      return meta.id;
    },
  });
  return json(job);
}

// ---------- 3D mesh generation ----------
// NOTE (2026-05): Krea's *public* OpenAPI spec at api.krea.ai/openapi.json does
// NOT currently document 3D endpoints, even though the Krea web app exposes
// image-to-3D in the UI. We optimistically POST to /generate/3d/<model> with the
// same job/poll shape image endpoints use. If Krea hasn't shipped this publicly
// yet, the call will 404 and we surface a clear error to the frontend rather
// than crashing. When they ship it (or we swap to Tripo / Meshy), the change is
// localized to kreaGenerate3d.

async function handleMeshGenerate(req: Request, env: Env, _ctx: ExecutionContext): Promise<Response> {
  const body = await req.json() as {
    sourceImageIds: string[];
    model?: string;
    // Per-model knobs (Meshy v6 polycount, pose_mode, etc). Adapter reads
    // whatever it cares about and ignores the rest.
    options?: Record<string, unknown>;
  };
  if (!body.sourceImageIds?.length) return err(400, "sourceImageIds required (>=1)");

  // Eagerly resolve sources — fail fast if any are missing.
  const sources = await Promise.all(
    body.sourceImageIds.map(id => env.STATE.get(`image:${id}`, "json") as Promise<ImageMeta | null>),
  );
  for (let i = 0; i < sources.length; i++) {
    if (!sources[i]) return err(404, `source image not found: ${body.sourceImageIds[i]}`);
  }

  const model = body.model || "fal-ai/hunyuan-3d/v3.1/pro/image-to-3d";
  const adapter = FAL_3D_MODELS[model];
  if (!adapter) {
    return err(400, `Unknown 3D model slug '${model}'. Known: ${Object.keys(FAL_3D_MODELS).join(", ")}`);
  }

  const sourcesToSend = adapter.multiImage ? sources : sources.slice(0, 1);
  const falSources: FalSource[] = await Promise.all(
    sourcesToSend.map(async (s, i) => ({
      uri: await r2ToDataUri(env, s!.r2Key),
      view: s!.view,
      isPrimary: i === 0 && !s!.parentImageId,
    })),
  );

  // Submit to fal synchronously. The submit itself is fast (POST + JSON
  // response). We do NOT keep a ctx.waitUntil polling loop — long-running
  // CF isolates get evicted, killing the poll mid-job. Instead, the JobMeta
  // carries the fal status_url + response_url, and each /api/job/:id GET
  // polls fal once (throttled). Per-request polling is robust against
  // isolate eviction because each poll is its own short-lived invocation.
  let submit;
  try {
    submit = await falSubmit(env.FAL_API_KEY, model, adapter.buildBody(falSources, body.options ?? {}));
  } catch (e) {
    return err(502, e instanceof Error ? e.message : String(e));
  }

  const id = crypto.randomUUID();
  const now = Date.now();
  const job: JobMeta = {
    id,
    kind: "mesh",
    status: "processing",
    progress: `fal ${model}: queued${submit.queue_position != null ? ` (pos ${submit.queue_position})` : ""}`,
    subjectId: sources[0]!.subjectId,
    parentImageId: body.sourceImageIds[0],
    params: body as unknown as Record<string, unknown>,
    falCancelUrl: submit.cancel_url,
    falStatusUrl: submit.status_url,
    falResponseUrl: submit.response_url,
    falModel: model,
    falKind: "mesh",
    falStatus: "IN_QUEUE",
    falQueuePosition: submit.queue_position,
    falLastPolledAt: now,
    createdAt: now,
    updatedAt: now,
  };
  await env.STATE.put(`job:${id}`, JSON.stringify(job));
  const idx = (await env.STATE.get(KV_JOB_INDEX, "json") as string[] | null) ?? [];
  idx.push(id);
  await env.STATE.put(KV_JOB_INDEX, JSON.stringify(idx));
  return json(job);
}

// Convert an R2-stored image to a base64 data URI suitable for fal.ai's
// `image_url` parameter. fal accepts both public URLs and data URIs on every
// image-to-3D model we support, and data URIs avoid the round-trip through
// fal's storage upload (and crucially work the same in `wrangler dev` where
// fal can't reach localhost).
async function r2ToDataUri(env: Env, r2Key: string): Promise<string> {
  const obj = await env.IMAGES.get(r2Key);
  if (!obj) throw new Error(`R2 object not found: ${r2Key}`);
  const buf = await obj.arrayBuffer();
  const contentType = obj.httpMetadata?.contentType || "image/png";
  return `data:${contentType};base64,${arrayBufferToBase64(buf)}`;
}

function arrayBufferToBase64(buf: ArrayBuffer): string {
  // Workers can't btoa() large strings via spread (call-stack overflow on
  // ~100KB+ buffers). Walk the buffer in 32K chunks.
  const bytes = new Uint8Array(buf);
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk) as unknown as number[]);
  }
  return btoa(binary);
}

// ---------- Mesh remesh (Hunyuan smart-topology) ---------------------------
// Takes an existing GLB (one we previously generated) and runs it through
// fal-ai/hunyuan-3d/v3.1/smart-topology for retopology. The input mesh is
// passed as a base64 data URI so this works in `wrangler dev` and prod with
// the same code path; smart-topology accepts both URLs and data URIs.

async function handleMeshRemesh(req: Request, env: Env, _ctx: ExecutionContext): Promise<Response> {
  const body = await req.json() as {
    sourceMeshId: string;
    model?: string;
    polygon_type?: "triangle" | "quadrilateral" | "quad";
    face_level?: "high" | "medium" | "low";
  };
  if (!body.sourceMeshId) return err(400, "sourceMeshId required");
  const source = await env.STATE.get(`mesh:${body.sourceMeshId}`, "json") as MeshMeta | null;
  if (!source) return err(404, "source mesh not found");

  const model = body.model || "fal-ai/hunyuan-3d/v3.1/smart-topology";
  const adapter = FAL_REMESH_MODELS[model];
  if (!adapter) {
    return err(400, `Unknown remesh model slug '${model}'. Known: ${Object.keys(FAL_REMESH_MODELS).join(", ")}`);
  }

  // Encode source mesh as data URI.
  const obj = await env.IMAGES.get(source.r2Key);
  if (!obj) return err(404, `R2 mesh object not found: ${source.r2Key}`);
  const buf = await obj.arrayBuffer();
  const ext = source.format === "obj" ? "obj" : "glb";
  const mime = ext === "obj" ? "model/obj" : "model/gltf-binary";
  const inputDataUri = `data:${mime};base64,${arrayBufferToBase64(buf)}`;

  let submit;
  try {
    submit = await falSubmit(env.FAL_API_KEY, model, adapter.buildBody({
      inputDataUri,
      inputFileType: ext === "obj" ? "obj" : "glb",
      topology: body.polygon_type ?? "triangle",
      density: body.face_level ?? "medium",
    }));
  } catch (e) {
    return err(502, e instanceof Error ? e.message : String(e));
  }

  const id = crypto.randomUUID();
  const now = Date.now();
  const job: JobMeta = {
    id,
    kind: "remesh",
    status: "processing",
    progress: `fal ${model}: queued${submit.queue_position != null ? ` (pos ${submit.queue_position})` : ""}`,
    // Stash the source mesh id + image lineage on params so the completion
    // step can build a proper MeshMeta with parentMeshId + sourceImageIds.
    params: { ...body, _sourceImageIds: source.sourceImageIds, _parentMeshId: source.id } as unknown as Record<string, unknown>,
    falCancelUrl: submit.cancel_url,
    falStatusUrl: submit.status_url,
    falResponseUrl: submit.response_url,
    falModel: model,
    falKind: "remesh",
    falStatus: "IN_QUEUE",
    falQueuePosition: submit.queue_position,
    falLastPolledAt: now,
    createdAt: now,
    updatedAt: now,
  };
  await env.STATE.put(`job:${id}`, JSON.stringify(job));
  const idx = (await env.STATE.get(KV_JOB_INDEX, "json") as string[] | null) ?? [];
  idx.push(id);
  await env.STATE.put(KV_JOB_INDEX, JSON.stringify(idx));
  return json(job);
}

async function handleMeshDelete(id: string, env: Env): Promise<Response> {
  const meta = await env.STATE.get(`mesh:${id}`, "json") as MeshMeta | null;
  if (!meta) return err(404, "mesh not found");
  await Promise.all([
    env.IMAGES.delete(meta.r2Key),
    env.STATE.delete(`mesh:${id}`),
  ]);
  const idx = (await env.STATE.get(KV_MESH_INDEX, "json") as string[] | null) ?? [];
  await env.STATE.put(KV_MESH_INDEX, JSON.stringify(idx.filter(x => x !== id)));
  return json({ ok: true });
}

function inferMeshExt(url: string, contentType: string): string {
  const lower = url.toLowerCase();
  if (lower.endsWith(".glb")) return "glb";
  if (lower.endsWith(".gltf")) return "gltf";
  if (lower.endsWith(".obj")) return "obj";
  if (lower.endsWith(".fbx")) return "fbx";
  if (lower.endsWith(".usdz")) return "usdz";
  if (contentType.includes("gltf-binary")) return "glb";
  if (contentType.includes("gltf+json")) return "gltf";
  return "glb";
}

// ---------- Job tracking ----------
// Generation hits Krea in two phases: kick off (fast), then poll until done
// (up to 5 minutes for 3D). Holding the HTTP connection open for the duration
// would lose all in-flight work on a page refresh. Instead, every generation
// becomes a persisted Job: we store the JobMeta in KV, kick off the work via
// `ctx.waitUntil`, and return the JobMeta to the frontend immediately. The
// frontend polls `/api/job/:id` for status. Pending jobs survive page refresh.

type JobUpdate = (progress: string, extra?: Partial<JobMeta>) => Promise<void>;

interface StartJobArgs {
  kind: JobMeta["kind"];
  subjectId?: string;
  parentImageId?: string;
  view?: string;
  params: Record<string, unknown>;
  runner: (update: JobUpdate) => Promise<string>; // returns the resultId
}

async function startJob(env: Env, ctx: ExecutionContext, args: StartJobArgs): Promise<JobMeta> {
  const id = crypto.randomUUID();
  const now = Date.now();
  const job: JobMeta = {
    id,
    kind: args.kind,
    status: "queued",
    subjectId: args.subjectId,
    parentImageId: args.parentImageId,
    view: args.view,
    params: args.params,
    createdAt: now,
    updatedAt: now,
  };
  await env.STATE.put(`job:${id}`, JSON.stringify(job));
  const idx = (await env.STATE.get(KV_JOB_INDEX, "json") as string[] | null) ?? [];
  idx.push(id);
  await env.STATE.put(KV_JOB_INDEX, JSON.stringify(idx));

  const update: JobUpdate = async (progress, extra) => {
    Object.assign(job, extra ?? {}, { progress, status: "processing", updatedAt: Date.now() });
    await env.STATE.put(`job:${id}`, JSON.stringify(job));
  };

  // Run the work *after* we respond to the HTTP request. ctx.waitUntil keeps
  // the worker alive long enough for this to complete (or be killed by the
  // platform's hard limit, in which case the job will be flagged stale by
  // handleState — see JOB_STALE_MS).
  ctx.waitUntil((async () => {
    try {
      await update("Starting…");
      const resultId = await args.runner(update);
      Object.assign(job, { status: "completed", resultId, progress: undefined, updatedAt: Date.now() });
      await env.STATE.put(`job:${id}`, JSON.stringify(job));
      // Drop the job from the active index once terminal — the record stays in
      // KV briefly so the frontend's last poll resolves cleanly, then is GC'd
      // by handleJobDelete or by handleState's stale-job sweeper.
      const liveIdx = (await env.STATE.get(KV_JOB_INDEX, "json") as string[] | null) ?? [];
      await env.STATE.put(KV_JOB_INDEX, JSON.stringify(liveIdx.filter(x => x !== id)));
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      Object.assign(job, { status: "failed", error: message, updatedAt: Date.now() });
      await env.STATE.put(`job:${id}`, JSON.stringify(job));
      const liveIdx = (await env.STATE.get(KV_JOB_INDEX, "json") as string[] | null) ?? [];
      await env.STATE.put(KV_JOB_INDEX, JSON.stringify(liveIdx.filter(x => x !== id)));
    }
  })());

  return job;
}

// Throttle for fal status polls. The frontend polls /api/job/:id every 2s;
// fal can be slow under load. Limit upstream polls to once per 2.5s per job
// so multiple frontend tabs don't 4x the rate.
const FAL_POLL_THROTTLE_MS = 2500;

async function handleJobGet(id: string, env: Env): Promise<Response> {
  let job = await env.STATE.get(`job:${id}`, "json") as JobMeta | null;
  if (!job) {
    console.log(`[job/${id.slice(0, 8)}] not found in KV`);
    return err(404, "job not found");
  }

  // For mesh/remesh jobs, drive fal polling from this request. This is the
  // robust path: each /api/job/:id GET is a fresh, short worker invocation,
  // so isolate eviction can't strand an in-flight job. Throttle so multiple
  // frontend polls don't hammer fal.
  const isFalDriven = (job.kind === "mesh" || job.kind === "remesh") && !!job.falStatusUrl;
  const sinceLastFalPoll = Date.now() - (job.falLastPolledAt ?? 0);
  if (isFalDriven && job.status !== "completed" && job.status !== "failed" && sinceLastFalPoll >= FAL_POLL_THROTTLE_MS) {
    job = await pollFalAndAdvance(env, job);
  }

  const ageMs = Date.now() - job.updatedAt;
  console.log(`[job/${id.slice(0, 8)}] ${job.status} fal=${job.falStatus ?? "-"} progress="${job.progress ?? ""}" age=${Math.round(ageMs / 1000)}s kind=${job.kind}`);

  // Inline the result for completed jobs so the frontend gets it in one round
  // trip and doesn't need a separate /api/state call.
  let result: ImageMeta | MeshMeta | null = null;
  if (job.status === "completed" && job.resultId) {
    if (job.kind === "mesh" || job.kind === "remesh") {
      result = await env.STATE.get(`mesh:${job.resultId}`, "json") as MeshMeta | null;
    } else {
      result = await env.STATE.get(`image:${job.resultId}`, "json") as ImageMeta | null;
    }
  }
  // Stale-job rewrite — only relevant for image jobs (which still use
  // ctx.waitUntil). Mesh/remesh self-heal via per-poll, so they shouldn't
  // ever go stale.
  if ((job.status === "queued" || job.status === "processing") && ageMs > JOB_STALE_MS) {
    return json({ ...job, status: "failed", error: "Job stalled — worker likely died mid-poll. Retry the generation.", result: null });
  }
  return json({ ...job, result });
}

async function handleJobDelete(id: string, env: Env): Promise<Response> {
  await env.STATE.delete(`job:${id}`);
  const idx = (await env.STATE.get(KV_JOB_INDEX, "json") as string[] | null) ?? [];
  await env.STATE.put(KV_JOB_INDEX, JSON.stringify(idx.filter(x => x !== id)));
  return json({ ok: true });
}

// Cancel an in-flight job. Fires fal's cancel URL (if we captured one) so
// the upstream work stops billing, then marks the JobMeta as failed with a
// user-friendly message. The runner continues polling for ~3s before fal
// returns CANCELLED and the runner's catch writes its own failure record —
// that final write may overwrite our message but the job is functionally
// dead by then. Frontend should drop the placeholder on the cancel response
// without waiting for the runner to settle.
async function handleJobCancel(id: string, env: Env): Promise<Response> {
  const job = await env.STATE.get(`job:${id}`, "json") as JobMeta | null;
  if (!job) return err(404, "job not found");

  let cancelHit = false;
  let cancelMsg: string | undefined;
  if (job.falCancelUrl) {
    try {
      const cRes = await fetch(job.falCancelUrl, {
        method: "PUT",
        headers: { "Authorization": `Key ${env.FAL_API_KEY}` },
      });
      cancelHit = cRes.ok || cRes.status === 202;
      if (!cancelHit) cancelMsg = `fal cancel returned ${cRes.status}: ${(await cRes.text()).slice(0, 200)}`;
    } catch (e) {
      cancelMsg = e instanceof Error ? e.message : String(e);
    }
  }

  const updated: JobMeta = {
    ...job,
    status: "failed",
    error: cancelHit
      ? "Cancelled by user"
      : `Cancelled by user (fal cancel best-effort: ${cancelMsg ?? "no cancel URL on this job"})`,
    progress: undefined,
    updatedAt: Date.now(),
  };
  await env.STATE.put(`job:${id}`, JSON.stringify(updated));
  // Drop from the active index so handleState doesn't keep walking it.
  const idx = (await env.STATE.get(KV_JOB_INDEX, "json") as string[] | null) ?? [];
  await env.STATE.put(KV_JOB_INDEX, JSON.stringify(idx.filter(x => x !== id)));
  return json({ ok: true, cancelHit });
}

// ---------- Shared image persistence ----------

async function persistGeneratedImage(
  env: Env,
  imageUrl: string | undefined,
  seed: number | undefined,
  fields: {
    subjectId: string;
    prompt: string;
    model: string;
    width: number;
    height: number;
    steps: number;
    parentImageId?: string;
    view?: string;
  },
): Promise<ImageMeta | null> {
  if (!imageUrl) return null;
  const imgRes = await fetch(imageUrl);
  if (!imgRes.ok) throw new Error(`Failed to fetch generated image: ${imgRes.status}`);
  const contentType = imgRes.headers.get("content-type") ?? "image/png";
  const ext = contentType.includes("jpeg") ? "jpg" : contentType.includes("webp") ? "webp" : "png";

  const id = crypto.randomUUID();
  const folder = fields.view ? `subjects/${fields.subjectId}/views` : `subjects/${fields.subjectId}`;
  const r2Key = `${folder}/${id}.${ext}`;
  const buf = await imgRes.arrayBuffer();
  await env.IMAGES.put(r2Key, buf, { httpMetadata: { contentType } });

  const meta: ImageMeta = {
    id,
    subjectId: fields.subjectId,
    r2Key,
    prompt: fields.prompt,
    model: fields.model,
    width: fields.width,
    height: fields.height,
    steps: fields.steps,
    seed,
    createdAt: Date.now(),
    favorite: false,
    parentImageId: fields.parentImageId,
    view: fields.view,
  };
  await env.STATE.put(`image:${id}`, JSON.stringify(meta));
  const index = (await env.STATE.get(KV_IMAGE_INDEX, "json") as string[] | null) ?? [];
  index.push(id);
  await env.STATE.put(KV_IMAGE_INDEX, JSON.stringify(index));
  return meta;
}

// ---------- Krea asset upload ----------
// styleImages[].url and Flux Kontext's imageUrl must be Krea-hosted asset URLs.
// Anything else gets rejected with "Invalid asset URL". So we fetch the source
// bytes, POST them to https://api.krea.ai/assets, cache the returned image_url
// in KV, and reuse on subsequent generations.

interface CachedAsset { url: string; width?: number; height?: number; }

async function ensureKreaAsset(env: Env, sourceUrl: string): Promise<CachedAsset> {
  // Already a Krea-hosted asset? pass through (no dims known).
  if (/^https?:\/\/[^/]*krea\.ai\//i.test(sourceUrl)) return { url: sourceUrl };

  const cacheKey = `asset-cache:${sourceUrl}`;
  const cached = await env.STATE.get(cacheKey, "json") as CachedAsset | string | null;
  if (cached) {
    // Backward compat: older cache entries are bare strings, not objects.
    if (typeof cached === "string") return { url: cached };
    return cached;
  }

  // Pull the bytes. For our own /refs/* paths we go through the ASSETS
  // binding directly so this works in `wrangler dev` (where Krea can't
  // reach localhost) and avoids a self-fetch round trip in prod.
  const u = new URL(sourceUrl);
  let bytesRes: Response;
  if (u.pathname.startsWith("/refs/")) {
    bytesRes = await env.ASSETS.fetch(new Request(sourceUrl));
  } else {
    bytesRes = await fetch(sourceUrl);
  }
  if (!bytesRes.ok) throw new Error(`Failed to load style ref ${sourceUrl}: ${bytesRes.status}`);
  const blob = await bytesRes.blob();

  const filename = u.pathname.split("/").pop() || "sprite.png";
  const entry = await uploadAssetToKrea(env.KREA_API_KEY, blob, filename, `style ref: ${sourceUrl}`);
  await env.STATE.put(cacheKey, JSON.stringify(entry));
  return entry;
}

async function kreaAssetFromR2(env: Env, r2Key: string): Promise<CachedAsset> {
  const cacheKey = `asset-cache:r2:${r2Key}`;
  const cached = await env.STATE.get(cacheKey, "json") as CachedAsset | null;
  if (cached) return cached;

  const obj = await env.IMAGES.get(r2Key);
  if (!obj) throw new Error(`R2 object not found: ${r2Key}`);
  const blob = await obj.blob();
  const filename = r2Key.split("/").pop() || "image.png";
  const entry = await uploadAssetToKrea(env.KREA_API_KEY, blob, filename, `derivative source: ${r2Key}`);
  await env.STATE.put(cacheKey, JSON.stringify(entry));
  return entry;
}

async function uploadAssetToKrea(apiKey: string, blob: Blob, filename: string, description: string): Promise<CachedAsset> {
  const fd = new FormData();
  fd.append("file", blob, filename);
  fd.append("description", description);
  const upRes = await fetch(`${KREA_BASE}/assets`, {
    method: "POST",
    headers: { "Authorization": `Bearer ${apiKey}` },
    body: fd,
  });
  if (!upRes.ok) {
    const text = await upRes.text();
    throw new Error(`Krea asset upload failed (${upRes.status}): ${text}`);
  }
  const data = await upRes.json() as { image_url?: string; width?: number; height?: number };
  if (!data.image_url) throw new Error(`Krea asset response missing image_url: ${JSON.stringify(data)}`);
  return { url: data.image_url, width: data.width, height: data.height };
}

// ---------- Krea image generation ----------
// docs: https://docs.krea.ai/developers/examples/text-to-image.md
// POST https://api.krea.ai/generate/image/<model>  -> { job_id, status, ... }
// GET  https://api.krea.ai/jobs/<job_id>           -> { status, result: { urls: [...] } }

interface KreaResult { urls: string[]; seed?: number; }

const STYLE_IMAGE_MODELS = new Set([
  "bfl/flux-1-dev",
  "google/nano-banana",
  "google/nano-banana-pro",
  "ideogram/ideogram-3",
]);
function supportsStyleImages(model: string): boolean {
  return STYLE_IMAGE_MODELS.has(model);
}

async function kreaGenerate(
  apiKey: string,
  model: string,
  params: {
    prompt: string;
    width: number;
    height: number;
    steps: number;
    styleImages?: { url: string; strength: number }[];
    imageUrl?: string;   // flux-kontext: single image to edit
    imageUrls?: string[]; // nano-banana: multi-image input
  },
  update?: JobUpdate,
): Promise<KreaResult> {
  if (!apiKey) throw new Error("KREA_API_KEY is not set on the worker");

  const body: Record<string, unknown> = {
    prompt: params.prompt,
    width: params.width,
    height: params.height,
  };
  if (model.includes("flux-1-dev") || model.includes("flux-1-krea-dev") || model.includes("flux-1-kontext-dev")) {
    body.steps = params.steps;
  }
  if (model === "bfl/flux-1.1-pro") {
    body.width = Math.min(params.width, 1440);
    body.height = Math.min(params.height, 1440);
  }
  if (params.styleImages?.length && supportsStyleImages(model)) {
    body.styleImages = params.styleImages;
  }
  if (params.imageUrl && model.includes("flux-1-kontext-dev")) {
    body.imageUrl = params.imageUrl;
  }
  if (params.imageUrls?.length && (model.includes("nano-banana") || model.includes("seedream") || model.includes("flux-1-kontext"))) {
    body.imageUrls = params.imageUrls;
  }

  return await pollKreaJob(apiKey, `${KREA_BASE}/generate/image/${model}`, body, update);
}

async function pollKreaJob(apiKey: string, startUrl: string, body: unknown, update?: JobUpdate): Promise<KreaResult> {
  const startRes = await fetch(startUrl, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!startRes.ok) {
    const text = await startRes.text();
    throw new Error(`Krea start failed (${startRes.status}) at ${startUrl}: ${text}`);
  }
  const start = await startRes.json() as { job_id: string; status: string; };
  if (!start.job_id) throw new Error(`Krea response missing job_id: ${JSON.stringify(start)}`);

  // Poll until done. Cap at 90s wall-time; Krea typical is <30s for flux-dev.
  // 3D models may need longer — see kreaGenerate3d for its own deadline.
  const deadline = Date.now() + 90_000;
  const startedAt = Date.now();
  let last: any = start;
  let pollCount = 0;
  while (Date.now() < deadline) {
    await new Promise(r => setTimeout(r, 2000));
    pollCount++;
    const pollRes = await fetch(`${KREA_BASE}/jobs/${start.job_id}`, {
      headers: { "Authorization": `Bearer ${apiKey}` },
    });
    if (!pollRes.ok) {
      const text = await pollRes.text();
      throw new Error(`Krea poll failed (${pollRes.status}): ${text}`);
    }
    last = await pollRes.json();
    const elapsed = Math.round((Date.now() - startedAt) / 1000);
    await update?.(`Krea status: ${last.status ?? "?"} · ${elapsed}s elapsed (poll ${pollCount})`);
    if (last.status === "completed" || last.completed_at) break;
    if (last.status === "failed" || last.status === "error" || last.status === "cancelled") {
      throw new Error(`Krea job failed: ${JSON.stringify(last)}`);
    }
  }

  const result = last?.result;
  const urls: string[] = result?.urls ?? (result?.url ? [result.url] : []);
  if (!urls.length) throw new Error(`Krea result missing urls: ${JSON.stringify(last)}`);
  return { urls, seed: result?.seed };
}

// ---------- fal.ai 3D generation ------------------------------------------
// Krea's public REST API doesn't expose 3D yet, so the 3D pipeline runs on
// fal.ai. fal's queue API is consistent across models, but each 3D model
// uses different field names for the image input and stashes the result in
// a different field. Adapters below normalize that.
//
// docs: https://fal.ai/docs/model-endpoints/queue
//   submit:  POST   https://queue.fal.run/<model-id>          → { request_id, status_url, response_url }
//   status:  GET    https://queue.fal.run/<model-id>/requests/<id>/status  → { status: IN_QUEUE | IN_PROGRESS | COMPLETED | FAILED, ... }
//   result:  GET    https://queue.fal.run/<model-id>/requests/<id>         → model-specific body
//   auth:    Authorization: Key <FAL_API_KEY>   (NOT Bearer)

const FAL_QUEUE_BASE = "https://queue.fal.run";

// A source image headed to a fal 3D model. The adapter uses `view` to slot
// derivative views into the right named field for models that accept them
// (Hunyuan Pro). For models that take a flat array (Rodin) we just enumerate.
interface FalSource {
  uri: string;        // base64 data URI
  view?: string;      // "front" | "three_quarter" | "back" | "top"  (undefined = primary favorite, side-elevation)
  isPrimary: boolean; // true if this is the favorite (the side-view we hearted)
}

interface Fal3dAdapter {
  buildBody: (sources: FalSource[], options?: Record<string, unknown>) => Record<string, unknown>;
  extractMeshUrl: (result: Record<string, unknown>) => string | undefined;
  multiImage: boolean;
}

// Adapters for mesh-to-mesh retopology models. Each takes a base64 GLB data
// URI plus normalized topology/density inputs and produces the model-specific
// body. Field names diverge across providers — Hunyuan uses input_file_url +
// polygon_type=quadrilateral + face_level enum; Meshy uses model_url +
// topology=quad + target_polycount integer.
interface FalRemeshAdapter {
  buildBody: (params: { inputDataUri: string; inputFileType: "glb" | "obj"; topology: string; density: string }) => Record<string, unknown>;
  extractMeshUrl: (result: Record<string, unknown>) => string | undefined;
}

const FAL_REMESH_MODELS: Record<string, FalRemeshAdapter> = {
  "fal-ai/hunyuan-3d/v3.1/smart-topology": {
    buildBody: ({ inputDataUri, inputFileType, topology, density }) => ({
      input_file_url: inputDataUri,
      input_file_type: inputFileType,
      polygon_type: topology === "quad" ? "quadrilateral" : "triangle",
      face_level: density, // low | medium | high
    }),
    extractMeshUrl: (r) => (r?.model_glb as { url?: string } | undefined)?.url,
  },
  "fal-ai/meshy/v5/remesh": {
    buildBody: ({ inputDataUri, topology, density }) => ({
      model_url: inputDataUri,
      topology: topology === "quadrilateral" ? "quad" : topology,
      // Meshy uses a polycount integer instead of a low/medium/high enum.
      // Map sensibly: low=10k, medium=30k (Meshy's default), high=100k.
      target_polycount: density === "low" ? 10_000 : density === "high" ? 100_000 : 30_000,
    }),
    extractMeshUrl: (r) =>
      (r?.model_glb as { url?: string } | undefined)?.url
      ?? ((r?.model_urls as Record<string, { url?: string }> | undefined)?.glb?.url),
  },
};

const FAL_3D_MODELS: Record<string, Fal3dAdapter> = {
  // Best-quality default. Hunyuan 3D 3.1 Pro accepts up to seven named view
  // slots (front/back/left/right/top/bottom/left_front/right_front) and
  // produces a textured glb with PBR materials. We map our derivative pipeline
  // (front/three_quarter/back/top) onto its named slots; the favorite (the
  // canonical side-elevation we hearted) goes into the slot that matches the
  // catalog facing — if a "front" derivative exists, the favorite slots in as
  // a side ref, otherwise the favorite IS the front. face_count caps geometry.
  "fal-ai/hunyuan-3d/v3.1/pro/image-to-3d": {
    buildBody: (sources) => {
      const body: Record<string, unknown> = {
        generate_type: "Normal",
        enable_pbr: true,
        face_count: 500_000,
      };
      const byView = new Map<string, FalSource>();
      let primary: FalSource | undefined;
      for (const s of sources) {
        if (s.isPrimary) primary = s;
        else if (s.view) byView.set(s.view, s);
      }
      const front = byView.get("front");
      // Required: input_image_url. Prefer the explicit "front" derivative if
      // present; otherwise fall back to the favorite (whose camera is a side
      // elevation but is the only thing we have).
      body.input_image_url = (front ?? primary)!.uri;
      if (front && primary) body.left_image_url = primary.uri;
      const back = byView.get("back");
      const top = byView.get("top");
      const tq = byView.get("three_quarter");
      if (back) body.back_image_url = back.uri;
      if (top) body.top_image_url = top.uri;
      if (tq) body.left_front_image_url = tq.uri;
      return body;
    },
    extractMeshUrl: (r) => (r?.model_glb as { url?: string } | undefined)?.url,
    multiImage: true,
  },
  // Mid-tier single-image model. Solid quality/cost balance.
  "fal-ai/trellis": {
    buildBody: (sources) => ({
      image_url: sources[0]!.uri,
      texture_size: 1024,
      mesh_simplify: 0.95,
    }),
    extractMeshUrl: (r) => (r?.model_mesh as { url?: string } | undefined)?.url,
    multiImage: false,
  },
  // Multi-view, premium. condition_mode "concat" requires multi-view of the
  // same subject; "fuse" combines features from disparate refs.
  "fal-ai/hyper3d/rodin": {
    buildBody: (sources) => ({
      input_image_urls: sources.map(s => s.uri),
      condition_mode: sources.length > 1 ? "concat" : "fuse",
      geometry_file_format: "glb",
      material: "PBR",
      quality: "medium",
    }),
    extractMeshUrl: (r) => (r?.model_mesh as { url?: string } | undefined)?.url,
    multiImage: true,
  },
  // Cheapest / fastest. Good for triage.
  "fal-ai/triposr": {
    buildBody: (sources) => ({
      image_url: sources[0]!.uri,
      output_format: "glb",
      do_remove_background: false, // our renders already have flat magenta bg
      foreground_ratio: 0.95,
      mc_resolution: 256,
    }),
    extractMeshUrl: (r) => (r?.model_mesh as { url?: string } | undefined)?.url,
    multiImage: false,
  },
  // Meshy v6. Single-image only but has the most exposed knobs of any fal
  // image-to-3d model: target_polycount, pose_mode, symmetry, PBR, internal
  // retopology. Reads inspector inputs from `options` (sent by the frontend).
  // Anything missing falls back to Meshy's defaults.
  "fal-ai/meshy/v6/image-to-3d": {
    buildBody: (sources, opts = {}) => {
      const body: Record<string, unknown> = {
        image_url: sources[0]!.uri,
        topology: opts.topology ?? "triangle",
        target_polycount: opts.target_polycount ?? 30_000,
        symmetry_mode: opts.symmetry_mode ?? "auto",
        should_remesh: opts.should_remesh ?? true,
        should_texture: true,
        enable_pbr: opts.enable_pbr ?? true,
        enable_safety_checker: false,
      };
      // pose_mode: "" / "a-pose" / "t-pose". Meshy expects empty string for
      // "none", which is also its default.
      const pose = (opts.pose_mode as string | undefined) ?? "";
      if (pose) body.pose_mode = pose;
      return body;
    },
    extractMeshUrl: (r) => (r?.model_glb as { url?: string } | undefined)?.url,
    multiImage: false,
  },
  // Hunyuan 2.1. Marked deprecated by fal but still callable.
  "fal-ai/hunyuan3d-v21": {
    buildBody: (sources) => ({
      input_image_url: sources[0]!.uri,
      textured_mesh: true,
      octree_resolution: 256,
    }),
    extractMeshUrl: (r) => (r?.model_glb as { url?: string } | undefined)?.url,
    multiImage: false,
  },
};

interface Fal3dResult { meshUrl: string; }

interface FalSubmitResponse {
  request_id: string;
  status_url: string;
  response_url: string;
  cancel_url?: string;
  queue_position?: number;
}

// Submit-only helper. Per-poll architecture (see JobMeta.falStatusUrl docs)
// means we never poll fal from inside ctx.waitUntil — handleJobGet does it.
async function falSubmit(apiKey: string, modelOrPath: string, body: Record<string, unknown>): Promise<FalSubmitResponse> {
  if (!apiKey) throw new Error("FAL_API_KEY is not set on the worker. Run: wrangler secret put FAL_API_KEY");
  const submitUrl = `${FAL_QUEUE_BASE}/${modelOrPath}`;
  const res = await fetch(submitUrl, {
    method: "POST",
    headers: {
      "Authorization": `Key ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`fal submit failed (${res.status}) at ${submitUrl}: ${text.slice(0, 500)}`);
  }
  const submit = await res.json() as FalSubmitResponse;
  if (!submit.request_id) throw new Error(`fal submit missing request_id: ${JSON.stringify(submit)}`);
  return submit;
}

// Poll fal once, advance the JobMeta, persist. Called from handleJobGet at
// most every 2.5s per job (throttle via falLastPolledAt). On COMPLETED,
// downloads the mesh + creates the MeshMeta inline. On FAILED/CANCELLED/
// ERROR, marks the job failed. Returns the (possibly mutated) job.
async function pollFalAndAdvance(env: Env, job: JobMeta): Promise<JobMeta> {
  if (!job.falStatusUrl || !job.falResponseUrl) return job;
  if (job.status === "completed" || job.status === "failed") return job;

  const apiKey = env.FAL_API_KEY;
  const sRes = await fetch(job.falStatusUrl, { headers: { "Authorization": `Key ${apiKey}` } });
  if (!sRes.ok) {
    // Don't terminally fail on a transient status hiccup — just log and bail.
    console.error(`[fal poll] ${job.id.slice(0,8)} status check failed: ${sRes.status}`);
    job.falLastPolledAt = Date.now();
    await env.STATE.put(`job:${job.id}`, JSON.stringify(job));
    return job;
  }
  const sBody = await sRes.json() as { status: string; queue_position?: number; error?: string };

  job.falStatus = sBody.status;
  job.falQueuePosition = sBody.queue_position;
  job.falLastPolledAt = Date.now();
  job.updatedAt = Date.now();

  const elapsed = Math.round((Date.now() - job.createdAt) / 1000);
  const queueHint = sBody.queue_position != null && sBody.status === "IN_QUEUE"
    ? ` (queue pos ${sBody.queue_position})` : "";
  job.progress = `fal ${job.falModel ?? "?"}: ${sBody.status}${queueHint} · ${elapsed}s`;

  if (sBody.status === "FAILED" || sBody.status === "ERROR" || sBody.status === "CANCELLED") {
    job.status = "failed";
    job.error = `fal job ${sBody.status}${sBody.error ? `: ${sBody.error}` : ""}`;
    job.progress = undefined;
  } else if (sBody.status === "COMPLETED") {
    // Fetch the result body, extract the mesh URL via the right adapter,
    // download the bytes, write to R2, create a MeshMeta. Any failure here
    // marks the job failed rather than leaving it stuck on COMPLETED.
    try {
      const rRes = await fetch(job.falResponseUrl, { headers: { "Authorization": `Key ${apiKey}` } });
      if (!rRes.ok) throw new Error(`fal result fetch failed (${rRes.status}): ${(await rRes.text()).slice(0, 300)}`);
      const result = await rRes.json() as Record<string, unknown>;

      let meshUrl: string | undefined;
      if (job.falKind === "remesh") {
        const remeshAdapter = FAL_REMESH_MODELS[job.falModel ?? ""];
        // Fall back to model_glb.url for older jobs that pre-date the
        // remesh-adapter table — Hunyuan's output is always there too.
        meshUrl = remeshAdapter?.extractMeshUrl(result)
          ?? (result?.model_glb as { url?: string } | undefined)?.url;
      } else if (job.falModel) {
        const adapter = FAL_3D_MODELS[job.falModel];
        meshUrl = adapter?.extractMeshUrl(result);
      }
      if (!meshUrl) throw new Error(`fal result missing mesh url for ${job.falModel ?? "?"}: ${JSON.stringify(result).slice(0, 300)}`);

      const meshRes = await fetch(meshUrl);
      if (!meshRes.ok) throw new Error(`mesh download failed: ${meshRes.status}`);
      const contentType = meshRes.headers.get("content-type") ?? "model/gltf-binary";
      const outExt = inferMeshExt(meshUrl, contentType);
      const meshId = crypto.randomUUID();
      const r2Key = `meshes/${meshId}.${outExt}`;
      const meshBuf = await meshRes.arrayBuffer();
      await env.IMAGES.put(r2Key, meshBuf, { httpMetadata: { contentType } });

      // sourceImageIds + parentMeshId come from `params` (mesh: top-level
      // sourceImageIds; remesh: stashed under _sourceImageIds + _parentMeshId
      // so the original request body stays clean).
      const params = job.params ?? {};
      const sourceImageIds: string[] = job.falKind === "remesh"
        ? ((params as { _sourceImageIds?: string[] })._sourceImageIds ?? [])
        : ((params as { sourceImageIds?: string[] }).sourceImageIds ?? []);
      const parentMeshId = job.falKind === "remesh"
        ? (params as { _parentMeshId?: string })._parentMeshId
        : undefined;

      const meta: MeshMeta = {
        id: meshId,
        sourceImageIds,
        r2Key,
        format: outExt,
        model: job.falModel ?? "(unknown)",
        createdAt: Date.now(),
        parentMeshId,
      };
      await env.STATE.put(`mesh:${meshId}`, JSON.stringify(meta));
      const meshIdx = (await env.STATE.get(KV_MESH_INDEX, "json") as string[] | null) ?? [];
      meshIdx.push(meshId);
      await env.STATE.put(KV_MESH_INDEX, JSON.stringify(meshIdx));

      job.status = "completed";
      job.resultId = meshId;
      job.progress = undefined;
    } catch (e) {
      job.status = "failed";
      job.error = e instanceof Error ? e.message : String(e);
      job.progress = undefined;
    }
  }

  await env.STATE.put(`job:${job.id}`, JSON.stringify(job));
  if (job.status === "completed" || job.status === "failed") {
    const idx = (await env.STATE.get(KV_JOB_INDEX, "json") as string[] | null) ?? [];
    await env.STATE.put(KV_JOB_INDEX, JSON.stringify(idx.filter(x => x !== job.id)));
  }
  return job;
}

// (Old `falGenerate3d` and `falRemesh` polling helpers were removed when the
// mesh + remesh pipelines moved to per-poll architecture. handleJobGet now
// drives fal status checks; pollFalAndAdvance is the only entry point.)
